# Generated by Django 2.1.2 on 2018-11-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181112_1034'),
        ('account', '0005_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='own_states',
            field=models.ManyToManyField(blank=True, help_text='Owned states for this user.', related_name='user_set', related_query_name='user', to='main.State', verbose_name='owned states'),
        ),
    ]
