# Generated by Django 2.1.2 on 2018-11-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.Country'),
        ),
    ]
