# Generated by Django 2.1.2 on 2018-11-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20181119_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='report_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.ReportPeriod'),
        ),
    ]
