# Generated by Django 2.1.2 on 2018-11-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20181119_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='ref_no',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
