# Generated by Django 2.1.2 on 2018-11-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20181120_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='file_date',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='cobal_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='fandc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='fare_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='pen',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='std_comm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='supp_comm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='tax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='tax_on_comm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='transaction_amount',
            field=models.FloatField(null=True),
        ),
    ]
