# Generated by Django 2.1.2 on 2018-11-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20181127_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='transaction',
        ),
        migrations.RenameField(
            model_name='charges',
            old_name='fare',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sales_total',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='agencydebitmemo',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='charges',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='gross_sales',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='net_sales',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='agencydebitmemo',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Transaction'),
        ),
        migrations.AddField(
            model_name='charges',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Transaction'),
        ),
        migrations.AddField(
            model_name='taxes',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cobl_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fare_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pen',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pen_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='std_comm_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='std_comm_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sup_comm_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sup_comm_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_on_comm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
