# Generated by Django 2.1.2 on 2018-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20181127_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
