# Generated by Django 2.1.2 on 2018-11-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0008_auto_20181127_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ca',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cpui',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ep',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fop',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stat',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
