# Generated by Django 2.1.2 on 2018-12-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_transaction_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydebitmemo',
            name='is_acm',
            field=models.BooleanField(default=False),
        ),
    ]
