# Generated by Django 2.1.2 on 2018-12-07 11:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_agencydebitmemo_is_acm'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agencydebitmemo',
            managers=[
                ('csv', django.db.models.manager.Manager()),
            ],
        ),
    ]
