# Generated by Django 2.1.2 on 2018-12-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20181207_1144'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportperiod',
            index=models.Index(fields=['ped', 'year', 'month'], name='report_repo_ped_3d44eb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['agency', 'report', 'transaction_type'], name='report_tran_agency__1523b6_idx'),
        ),
        migrations.AddIndex(
            model_name='charges',
            index=models.Index(fields=['transaction'], name='report_char_transac_836b64_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfile',
            index=models.Index(fields=['report_period', 'airline'], name='report_repo_report__78211c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxes',
            index=models.Index(fields=['transaction'], name='report_taxe_transac_67e544_idx'),
        ),
        migrations.AddIndex(
            model_name='agencydebitmemo',
            index=models.Index(fields=['transaction'], name='report_agen_transac_605d2c_idx'),
        ),
    ]
