# Generated by Django 2.1.2 on 2018-12-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20181211_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='acms',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='ca',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='cc',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
