# Generated by Django 2.1.2 on 2018-12-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_dailycreditcardfile'),
        ('report', '0014_auto_20181217_1053'),
    ]

    operations = [
    ]
