# Generated by Django 2.1.2 on 2018-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20181217_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ped', models.DateField(unique=True)),
                ('remittance', models.DateField(unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['ped'], name='report_remi_ped_6ffaf4_idx'),
        ),
    ]
