# Generated by Django 2.1.2 on 2018-12-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20181218_1357'),
        ('report', '0015_merge_20181218_1413'),
    ]

    operations = [
    ]
