# Generated by Django 2.1.2 on 2018-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_merge_20181219_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydebitmemo',
            name='allowed_commission_amount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
