# Generated by Django 2.1.2 on 2019-01-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_agencydebitmemo_allowed_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
