# Generated by Django 2.1.2 on 2019-01-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_reprocessfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reprocessfile',
            old_name='is_dine',
            new_name='is_done',
        ),
    ]
