# Generated by Django 2.1.2 on 2019-01-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_airline_accepts_uatp'),
        ('report', '0025_auto_20190124_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprocessfile',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Airline'),
        ),
        migrations.AddField(
            model_name='reprocessfile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reprocessfile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
