# Generated by Django 2.1.2 on 2019-01-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_auto_20190124_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id']},
        ),
    ]
