# Generated by Django 2.1.2 on 2019-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_auto_20190124_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='std_comm_rate',
            field=models.FloatField(null=True),
        ),
    ]
