# Generated by Django 2.1.2 on 2019-02-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0031_auto_20190212_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='international',
            field=models.BooleanField(default=False),
        ),
    ]
