# Generated by Django 2.1.2 on 2019-02-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0034_auto_20190225_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='bank7',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='arc_deduction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='arc_fees',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='arc_reversal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='arc_tot',
            field=models.FloatField(default=0.0),
        ),
    ]
