# Generated by Django 2.1.2 on 2019-02-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0035_auto_20190226_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('amount', models.FloatField(null=True)),
                ('pending', models.BooleanField(default=False)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.CarrierDeductions')),
            ],
        ),
    ]
