# Generated by Django 2.1.2 on 2019-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0037_auto_20190311_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pen_type',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
