# Generated by Django 2.1.2 on 2019-03-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0038_auto_20190312_0709'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'ticket_no', 'issue_date', 'transaction_amount', 'fare_amount', 'pen', 'pen_type', 'cobl_amount', 'std_comm_rate', 'std_comm_amount', 'sup_comm_rate', 'sup_comm_amount', 'tax_on_comm', 'balance', 'cpui', 'stat', 'fop', 'cc', 'ca', 'ep', 'card_type', 'card_code', 'international'], name='report_tran_transac_153418_idx'),
        ),
    ]
