# Generated by Django 2.1.2 on 2019-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0039_auto_20190320_1051'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taxes',
            name='report_taxe_transac_67e544_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportfile',
            name='report_repo_report__78211c_idx',
        ),
        migrations.RemoveIndex(
            model_name='charges',
            name='report_char_transac_836b64_idx',
        ),
        migrations.AddIndex(
            model_name='taxes',
            index=models.Index(fields=['transaction', 'amount', 'type'], name='report_taxe_transac_f834de_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfile',
            index=models.Index(fields=['report_period', 'airline', 'transaction_amount', 'fare_amount', 'tax', 'fandc', 'pen', 'cobl_amount', 'std_comm', 'supp_comm', 'tax_on_comm', 'balance', 'acms', 'cc', 'ca'], name='report_repo_report__3ded25_idx'),
        ),
        migrations.AddIndex(
            model_name='charges',
            index=models.Index(fields=['transaction', 'amount', 'type'], name='report_char_transac_e70e0d_idx'),
        ),
    ]
