# Generated by Django 2.1.2 on 2019-03-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0040_auto_20190320_1157'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportperiod',
            name='report_repo_ped_3d44eb_idx',
        ),
        migrations.AddIndex(
            model_name='reportperiod',
            index=models.Index(fields=['ped', 'year', 'month', 'from_date', 'country'], name='report_repo_ped_c0edb7_idx'),
        ),
    ]
