# Generated by Django 2.1.2 on 2019-05-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0041_auto_20190320_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycreditcardfile',
            name='grand_total',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
