# Generated by Django 2.1.2 on 2019-05-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0044_auto_20190521_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydebitmemo',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Transaction', unique=True),
        ),
    ]
