# Generated by Django 2.1.2 on 2020-10-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0048_auto_20190704_0731'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='report_tran_agency__1523b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='report_tran_transac_153418_idx',
        ),
    ]
