# Generated by Django 2.1.2 on 2018-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_state_statefilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statefilter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='statefilter',
            name='list_of_states',
        ),
        migrations.RemoveField(
            model_name='statefilter',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='StateFilter',
        ),
    ]
