# Generated by Django 2.1.2 on 2018-10-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
