# Generated by Django 2.1.2 on 2018-11-05 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='product_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_airlines', to=settings.AUTH_USER_MODEL),
        ),
    ]
