# Generated by Django 2.1.2 on 2018-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='abcs_commision',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='distribution_fee',
        ),
        migrations.AddField(
            model_name='airline',
            name='iata_coordination_fee',
            field=models.FloatField(default=3.0, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='arc_coordination_fee',
            field=models.FloatField(default=0.0, verbose_name='ARC Coordination Fee (%)'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='gsa_commision',
            field=models.FloatField(default=3.0, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='max_commission_rate',
            field=models.FloatField(default=3.0, null=True),
        ),
    ]
