# Generated by Django 2.1.2 on 2018-11-14 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181112_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to=settings.AUTH_USER_MODEL),
        ),
    ]
