# Generated by Django 2.1.2 on 2018-11-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181115_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',), 'permissions': (('view_stateowners', 'Can view state owners list'), ('change_stateowners', 'Can change state owners'))},
        ),
    ]
