# Generated by Django 2.1.2 on 2018-11-27 13:38

from django.db import migrations


def country_import(apps, schema_editor):
    countries = [
        {'name': 'Canada', 'code': 'CA', 'states': [
            ('Ontario', 'ON'),
            ('Quebec', 'QC'),
            ('Nova Scotia', 'NS'),
            ('New Brunswick', 'NB'),
            ('Manitoba', 'MB'),
            ('British Columbia', 'BC'),
            ('Prince Edward Island', 'PE'),
            ('Saskatchewan', 'SK'),
            ('Alberta', 'AB'),
            ('Newfoundland and Labrador', 'NL'),
            ('Yukon', 'YT'),
            ('Northwest Territories', 'NT'),
            ('Nunavut', 'NU'),
            ('Canada', 'CA'),
        ]},
        {'name': 'United States', 'code': 'US', 'states': [
            ('Alabama', 'AL'),
            ('Alaska', 'AK'),
            ('Arizona', 'AZ'),
            ('Arkansas', 'AR'),
            ('California', 'CA'),
            ('Colorado', 'CO'),
            ('Connecticut', 'CT'),
            ('Delaware', 'DE'),
            ('Florida', 'FL'),
            ('Georgia', 'GA'),
            ('Hawaii', 'HI'),
            ('Idaho', 'ID'),
            ('Illinois', 'IL'),
            ('Indiana', 'IN'),
            ('Iowa', 'IA'),
            ('Kansas', 'KS'),
            ('Kentucky', 'KY'),
            ('Louisiana', 'LA'),
            ('Maine', 'ME'),
            ('Maryland ', 'MD'),
            ('Massachusett', 'MA'),
            ('Michigan', 'MI'),
            ('Minnesota', 'MN'),
            ('Mississippi', 'MS'),
            ('Missouri', 'MO'),
            ('Montana', 'MT'),
            ('Nebraska', 'NE'),
            ('Nevada', 'NV'),
            ('New Hampshire', 'NH'),
            ('New Jersey', 'NJ'),
            ('New Mexico', 'NM'),
            ('New York', 'NY'),
            ('North Carolina', 'NC'),
            ('North Dakota', 'ND'),
            ('Ohio', 'OH'),
            ('Oklahoma', 'OK'),
            ('Oregon', 'OR'),
            ('Pennsylvania', 'PA'),
            ('Rhode Island', 'RI'),
            ('South Carolina', 'SC'),
            ('South Dakota', 'SD'),
            ('Tennessee', 'TN'),
            ('Texas', 'TX'),
            ('Utah', 'UT'),
            ('Vermont', 'VT'),
            ('Virginia', 'VA'),
            ('Washington', 'WA'),
            ('West Virginia', 'WV'),
            ('Wisconsin', 'WI'),
            ('Wyoming', 'WY'),
            ('Puerto Rico', 'PR'),
            ('Virgin Islands', 'VI'),
            ('Guam', 'GU'),
            ('Northern Mariana Islands', 'MP'),
            ('American Samoa', 'AS'),
            ('District of Columbia', 'DC'),
            ('Federated States of Micronesia', 'FM'),
            ('Marshall Islands', 'MH'),
            ('Palau', 'PW'),
            ('Armed Forces Africa', 'AE'),
            ('Armed Forces Americas', 'AA'),
            ('Armed Forces Canada', 'AE'),
            ('Armed Forces Europe', 'AE'),
            ('Armed Forces Middle East', 'AE'),
            ('Armed Forces Pacific', 'AP'),
            ('American Samoa', 'AS'),
            ('District of Columbia', 'DC'),
            ('Federated States of Micronesia', 'FM'),
            ('Marshall Islands', 'MH'),
            ('Palau', 'PW'),
            ('Armed Forces Africa', 'AE'),
            ('Armed Forces Americas', 'AA'),
            ('Armed Forces Canada', 'AE'),
            ('Armed Forces Europe', 'AE'),
            ('Armed Forces Middle East', 'AE'),
            ('Armed Forces Pacific', 'AP'),
        ]},
    ]

    for country in countries:
        Country = apps.get_model('main', 'Country')
        State = apps.get_model('main', 'State')
        c, created = Country.objects.get_or_create(
                name=country.get('name'),
                defaults={
                    'code': country.get('code'),
                }
            )
        for state in country.get('states'):
            st, created = State.objects.get_or_create(
                name=state[0],
                defaults={
                    'abrev': state[1],
                    'country': c
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181127_1211'),
    ]

    operations = [
        migrations.RunPython(country_import),
    ]
