# Generated by Django 2.1.2 on 2018-11-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20181127_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'permissions': (('view_stateowners', 'Can view state owners list'), ('change_stateowners', 'Can change state owners'))},
        ),
        migrations.AddField(
            model_name='airline',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='main.Country'),
        ),
    ]
