# Generated by Django 2.1.2 on 2018-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20181128_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='abrev',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='airline',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='airline',
            unique_together={('country', 'code', 'abrev')},
        ),
    ]
