# Generated by Django 2.1.2 on 2018-12-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20181128_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('abrev',), 'permissions': (('view_stateowners', 'Can view state owners list'), ('change_stateowners', 'Can change state owners'))},
        ),
    ]
