# Generated by Django 2.1.2 on 2018-12-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20181204_0711'),
        ('main', '0020_auto_20181204_0713'),
    ]

    operations = [
    ]
