# Generated by Django 2.1.2 on 2018-12-20 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20181210_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_airlines', to=settings.AUTH_USER_MODEL),
        ),
    ]
