# Generated by Django 2.1.2 on 2019-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20181220_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='accepts_UATP',
            field=models.NullBooleanField(),
        ),
    ]
