# Generated by Django 2.1.2 on 2019-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_commissionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionhistory',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commissionhistory',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
