# Generated by Django 2.1.2 on 2019-02-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190211_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionhistory',
            name='type',
            field=models.CharField(blank=True, choices=[('M', 'Max Sales commission'), ('G', 'GSA Commission'), ('I', 'IATA Coordination Fee'), ('D', 'Distribution Intermediary Fee'), ('A', 'ARC coordination fee')], max_length=1, null=True),
        ),
    ]
