# Generated by Django 2.1.2 on 2020-04-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190228_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='CA', max_length=4),
            preserve_default=False,
        ),
    ]
