# Generated by Django 2.1.2 on 2020-11-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_ftphistory'),
        ('main', '0030_auto_20201012_0943'),
    ]

    operations = [
    ]
