# Generated by Django 2.1.2 on 2018-10-31 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20181031_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='agency.AgencyType'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='sales_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agencies', to=settings.AUTH_USER_MODEL),
        ),
    ]
