# Generated by Django 2.1.2 on 2018-11-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20181031_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencylistreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agencylistreference',
            name='processed_at',
            field=models.DateTimeField(auto_now=True, unique=True),
        ),
    ]
