# Generated by Django 2.1.2 on 2018-11-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20181107_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address1',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='trade_name',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
