# Generated by Django 2.1.2 on 2018-11-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20181107_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
