# Generated by Django 2.1.2 on 2018-11-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_auto_20181107_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address2',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='home_agency',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
