# Generated by Django 2.1.2 on 2018-11-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_state_country'),
        ('agency', '0011_remove_agency_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.State'),
        ),
    ]
