# Generated by Django 2.1.2 on 2018-11-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_agency_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('D', 'Defaulted'), ('R', 'Revoked'), ('S', 'Reinstated'), ('T', 'Terminated')], default='A', max_length=1, null=True),
        ),
    ]
