# Generated by Django 2.1.2 on 2018-11-12 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_auto_20181108_1337'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agency',
            managers=[
                ('csv', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.City'),
        ),
    ]
