# Generated by Django 2.1.2 on 2018-11-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_auto_20181112_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencylistreference',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'Agency List'), (2, 'Revokation/Reinstatment')], default=1),
        ),
    ]
