# Generated by Django 2.1.2 on 2018-11-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_agency_status_iata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencytype',
            name='name',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
