# Generated by Django 2.1.2 on 2018-11-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_auto_20181114_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
