# Generated by Django 2.1.2 on 2018-12-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20181210_1001'),
        ('agency', '0019_auto_20181122_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together={('agency_no', 'country')},
        ),
    ]
