# Generated by Django 2.1.2 on 2019-01-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_auto_20190114_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='trade_name',
            field=models.CharField(max_length=199, null=True),
        ),
    ]
