# Generated by Django 2.1.2 on 2019-04-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_auto_20190115_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_no',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
